name: Unit Tests
# This workflow is triggered on pushes to the repository.
on: [push, pull_request]

jobs:
  test:
    name: Test
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.14'
      - run: go version
      - run: make test
        env:
          GO111MODULE: "on"
      - uses: codecov/codecov-action@v1
        with:
          file: ./coverage.out

  build:
    name: Build
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build docker image
        run: docker build .
        env:
          GO111MODULE: "on"
